import { supabase } from '../../utils/supabase.js';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const HASH=/^[a-f0-9]{64}$/; const COUNTRY=/^[A-Z]{2}$/;
export interface CreateInvestmentSubscriptionCommand { organizationId:string; actorId:string; productId:string; requestedAmountMinor:number; investorCountry:string; investorType:'individual'|'group'|'organization'; acceptedRiskDisclosureVersion:string; acceptedRiskDisclosureHash:string; correlationId:string; idempotencyKey:string; }
export interface SettleInvestmentSubscriptionCommand { organizationId:string; actorId:string; subscriptionId:string; settlementId:string; correlationId:string; idempotencyKey:string; }
export interface AllocateInvestmentUnitsCommand { organizationId:string; actorId:string; subscriptionId:string; correlationId:string; idempotencyKey:string; }
export interface InvestmentSubscriptionGateway { create(command:CreateInvestmentSubscriptionCommand):Promise<unknown>; settle(command:SettleInvestmentSubscriptionCommand):Promise<unknown>; allocate(command:AllocateInvestmentUnitsCommand):Promise<unknown>; }
export class InvestmentSubscriptionValidationError extends Error { constructor(message:string){super(message);this.name='InvestmentSubscriptionValidationError';} }
export class SupabaseInvestmentSubscriptionGateway implements InvestmentSubscriptionGateway { private async rpc(name:string,args:Record<string,unknown>){const {data,error}=await supabase.rpc(name,args);if(error||data===null)throw error??new Error('Investment subscription storage returned no result.');return data;} create(c:CreateInvestmentSubscriptionCommand){return this.rpc('create_investment_subscription_intent',{p_organization:c.organizationId,p_actor:c.actorId,p_product:c.productId,p_amount_minor:c.requestedAmountMinor,p_country:c.investorCountry,p_investor_type:c.investorType,p_disclosure_version:c.acceptedRiskDisclosureVersion,p_disclosure_hash:c.acceptedRiskDisclosureHash,p_correlation:c.correlationId,p_idempotency_key:c.idempotencyKey});} settle(c:SettleInvestmentSubscriptionCommand){return this.rpc('settle_investment_subscription',{p_organization:c.organizationId,p_actor:c.actorId,p_subscription:c.subscriptionId,p_settlement:c.settlementId,p_correlation:c.correlationId,p_idempotency_key:c.idempotencyKey});} allocate(c:AllocateInvestmentUnitsCommand){return this.rpc('allocate_fixed_investment_units',{p_organization:c.organizationId,p_actor:c.actorId,p_subscription:c.subscriptionId,p_correlation:c.correlationId,p_idempotency_key:c.idempotencyKey});} }
export class InvestmentSubscriptionService { constructor(private readonly gateway:InvestmentSubscriptionGateway=new SupabaseInvestmentSubscriptionGateway()){} create(c:CreateInvestmentSubscriptionCommand){this.identity(c.organizationId,c.actorId,c.productId,c.correlationId,c.idempotencyKey);if(!Number.isSafeInteger(c.requestedAmountMinor)||c.requestedAmountMinor<=0)throw new InvestmentSubscriptionValidationError('Subscription amount must be positive integer minor units.');if(!COUNTRY.test(c.investorCountry)||!['individual','group','organization'].includes(c.investorType)||!HASH.test(c.acceptedRiskDisclosureHash)||typeof c.acceptedRiskDisclosureVersion!=='string'||c.acceptedRiskDisclosureVersion.trim().length<1||c.acceptedRiskDisclosureVersion.trim().length>80)throw new InvestmentSubscriptionValidationError('Subscription eligibility or disclosure evidence is invalid.');return this.gateway.create(c);} settle(c:SettleInvestmentSubscriptionCommand){this.identity(c.organizationId,c.actorId,c.subscriptionId,c.correlationId,c.idempotencyKey);if(!UUID.test(c.settlementId))throw new InvestmentSubscriptionValidationError('Settlement evidence identity is invalid.');return this.gateway.settle(c);} allocate(c:AllocateInvestmentUnitsCommand){this.identity(c.organizationId,c.actorId,c.subscriptionId,c.correlationId,c.idempotencyKey);return this.gateway.allocate(c);} private identity(org:string,actor:string,record:string,correlation:string,key:string){if(!UUID.test(org)||!UUID.test(actor)||!UUID.test(record)||!UUID.test(correlation)||typeof key!=='string'||key.length<8||key.length>160)throw new InvestmentSubscriptionValidationError('Subscription command identity is invalid.');} }
export const investmentSubscriptionService=new InvestmentSubscriptionService();
