import { supabase } from '../../utils/supabase.js';
const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export interface ProposeLoanRestructureCommand {organizationId:string;actorId:string;applicationId:string;contractId:string;effectiveDate:string;firstDueDate:string;installmentCount:number;reasonCode:string;reason:string;evidenceReferences:unknown[];correlationId:string;idempotencyKey:string;}
export interface DecideLoanRestructureCommand {organizationId:string;actorId:string;restructureId:string;decision:'approve'|'reject';reviewReason:string;correlationId:string;idempotencyKey:string;}
export interface LoanRestructuringGateway {propose(command:ProposeLoanRestructureCommand):Promise<unknown>;decide(command:DecideLoanRestructureCommand):Promise<unknown>;}
export class LoanRestructuringValidationError extends Error {constructor(message:string){super(message);this.name='LoanRestructuringValidationError';}}
export class SupabaseLoanRestructuringGateway implements LoanRestructuringGateway {
  async propose(c:ProposeLoanRestructureCommand){const {data,error}=await supabase.rpc('propose_loan_restructure',{p_organization:c.organizationId,p_actor:c.actorId,p_application:c.applicationId,p_contract:c.contractId,p_effective_date:c.effectiveDate,p_first_due_date:c.firstDueDate,p_installment_count:c.installmentCount,p_reason_code:c.reasonCode,p_reason:c.reason,p_evidence:c.evidenceReferences,p_correlation:c.correlationId,p_idempotency_key:c.idempotencyKey});if(error||data===null)throw error??new Error('Loan restructuring storage returned no result.');return data;}
  async decide(c:DecideLoanRestructureCommand){const {data,error}=await supabase.rpc('decide_loan_restructure',{p_organization:c.organizationId,p_actor:c.actorId,p_restructure:c.restructureId,p_decision:c.decision,p_review_reason:c.reviewReason,p_correlation:c.correlationId,p_idempotency_key:c.idempotencyKey});if(error||data===null)throw error??new Error('Loan restructuring decision storage returned no result.');return data;}
}
export class LoanRestructuringService {
  constructor(private readonly gateway:LoanRestructuringGateway=new SupabaseLoanRestructuringGateway()){}
  propose(c:ProposeLoanRestructureCommand){this.ids([['Organization ID',c.organizationId],['Actor ID',c.actorId],['Application ID',c.applicationId],['Contract ID',c.contractId],['Correlation ID',c.correlationId]]);this.date(c.effectiveDate,'Effective date');this.date(c.firstDueDate,'First due date');if(c.firstDueDate<c.effectiveDate)throw new LoanRestructuringValidationError('First due date cannot precede the effective date.');if(!Number.isInteger(c.installmentCount)||c.installmentCount<1||c.installmentCount>600)throw new LoanRestructuringValidationError('Installment count must be between 1 and 600.');if(!/^[A-Z][A-Z0-9_]{2,39}$/.test(c.reasonCode))throw new LoanRestructuringValidationError('Reason code is invalid.');if(c.reason.trim().length<12||c.reason.trim().length>500)throw new LoanRestructuringValidationError('Reason must contain 12 to 500 characters.');if(!Array.isArray(c.evidenceReferences)||c.evidenceReferences.length===0)throw new LoanRestructuringValidationError('Evidence references are required.');this.key(c.idempotencyKey);return this.gateway.propose(c);}
  decide(c:DecideLoanRestructureCommand){this.ids([['Organization ID',c.organizationId],['Actor ID',c.actorId],['Restructure ID',c.restructureId],['Correlation ID',c.correlationId]]);if(!['approve','reject'].includes(c.decision))throw new LoanRestructuringValidationError('Decision is invalid.');if(c.reviewReason.trim().length<12||c.reviewReason.trim().length>500)throw new LoanRestructuringValidationError('Review reason must contain 12 to 500 characters.');this.key(c.idempotencyKey);return this.gateway.decide(c);}
  private ids(values:Array<[string,string]>){for(const [label,value] of values)if(!UUID_PATTERN.test(value))throw new LoanRestructuringValidationError(`${label} must be a valid UUID.`);}
  private date(value:string,label:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value+'T00:00:00Z')))throw new LoanRestructuringValidationError(`${label} is invalid.`);}
  private key(value:string){if(value.length<8||value.length>160)throw new LoanRestructuringValidationError('Idempotency key must contain 8 to 160 characters.');}
}
export const loanRestructuringService=new LoanRestructuringService();
