import { InvestmentRefundSubmissionGateway,InvestmentRefundSubmissionService } from '../domains/financial/investmentRefundSubmissionService.js';
const command={organizationId:'00000000-0000-4000-8000-000000000101',actorId:'00000000-0000-4000-8000-000000000102',obligationId:'00000000-0000-4000-8000-000000000103',correlationId:'00000000-0000-4000-8000-000000000104',idempotencyKey:'investment-refund-submit-001'};
const prepared=(environment:'deterministic'|'sandbox'|'live'='deterministic')=>({replayed:false,attempt:{id:'00000000-0000-4000-8000-000000000105',state:'prepared',provider_name:environment==='deterministic'?'deterministic':'paystack',provider_environment:environment},obligation:{id:command.obligationId,amount_minor:100000,currency:'NGN' as const},provider_payment_reference:'SET-ORIGINAL-001'});
const gateway=():jest.Mocked<InvestmentRefundSubmissionGateway>=>({begin:jest.fn(),complete:jest.fn()});
describe('InvestmentRefundSubmissionService',()=>{
 it('submits exact money through the original adapter but does not finalize synchronous provider success',async()=>{const g=gateway();g.begin.mockResolvedValue(prepared());g.complete.mockResolvedValue({attempt:{state:'processing'}});const refund=jest.fn().mockResolvedValue({providerReference:'DET-REF-001',status:'succeeded',amountMinor:100000,currency:'NGN'});const adapter={name:'deterministic',environment:'deterministic',refund} as any;await expect(new InvestmentRefundSubmissionService(g,()=>adapter).submit(command)).resolves.toEqual({attempt:{state:'processing'}});expect(refund).toHaveBeenCalledWith(expect.objectContaining({providerPaymentReference:'SET-ORIGINAL-001',amountMinor:100000,currency:'NGN'}));expect(g.complete).toHaveBeenCalledWith(expect.objectContaining({state:'processing',providerReportedState:'succeeded',providerReference:'DET-REF-001'}));});
 it('records ambiguous provider submission as unknown for later recovery',async()=>{const g=gateway();g.begin.mockResolvedValue(prepared());g.complete.mockResolvedValue({attempt:{state:'unknown'}});const adapter={name:'deterministic',environment:'deterministic',refund:jest.fn().mockRejectedValue(new Error('timeout'))} as any;await new InvestmentRefundSubmissionService(g,()=>adapter).submit(command);expect(g.complete).toHaveBeenCalledWith(expect.objectContaining({state:'unknown',failureCode:'provider_response_ambiguous'}));});
 it('sends money mismatches and unavailable original routes to manual review',async()=>{const g=gateway();g.begin.mockResolvedValue(prepared());g.complete.mockResolvedValue({attempt:{state:'manual_review'}});const mismatch={name:'deterministic',environment:'deterministic',refund:jest.fn().mockResolvedValue({status:'processing',amountMinor:99999,currency:'NGN'})} as any;await new InvestmentRefundSubmissionService(g,()=>mismatch).submit(command);expect(g.complete).toHaveBeenLastCalledWith(expect.objectContaining({state:'manual_review',failureCode:'provider_money_mismatch'}));g.begin.mockResolvedValue(prepared('sandbox'));await new InvestmentRefundSubmissionService(g,()=>mismatch).submit(command);expect(g.complete).toHaveBeenLastCalledWith(expect.objectContaining({state:'manual_review',failureCode:'original_provider_unavailable'}));});
 it('records incomplete provider configuration instead of leaving a prepared attempt stuck',async()=>{const g=gateway();g.begin.mockResolvedValue(prepared());g.complete.mockResolvedValue({attempt:{state:'manual_review'}});await new InvestmentRefundSubmissionService(g,()=>{throw new Error('missing credentials');}).submit(command);expect(g.complete).toHaveBeenCalledWith(expect.objectContaining({state:'manual_review',failureCode:'provider_configuration_incomplete'}));});
 it('keeps live submission disabled and does not resubmit a durable replay',async()=>{const g=gateway();g.complete.mockResolvedValue({attempt:{state:'manual_review'}});g.begin.mockResolvedValue(prepared('live'));const factory=jest.fn();await new InvestmentRefundSubmissionService(g,factory as any).submit(command);expect(factory).not.toHaveBeenCalled();expect(g.complete).toHaveBeenCalledWith(expect.objectContaining({state:'manual_review',failureCode:'live_submission_not_activated'}));g.begin.mockResolvedValue({...prepared(),attempt:{...prepared().attempt,state:'processing'}});await expect(new InvestmentRefundSubmissionService(g,factory as any).submit(command)).resolves.toMatchObject({attempt:{state:'processing'}});});
 it('does not resubmit an idempotent replay while its durable attempt is still prepared',async()=>{const g=gateway();g.begin.mockResolvedValue({...prepared(),replayed:true});const factory=jest.fn();await expect(new InvestmentRefundSubmissionService(g,factory as any).submit(command)).resolves.toMatchObject({attempt:{state:'prepared'}});expect(factory).not.toHaveBeenCalled();expect(g.complete).not.toHaveBeenCalled();});
 it('rejects malformed tenant and command identities before storage',()=>{expect(()=>new InvestmentRefundSubmissionService(gateway()).submit({...command,obligationId:'bad'})).rejects.toThrow('identity');});
});
