-- AC-06 permission-checked, journal-derived member account statements.
SET search_path=public,extensions;
CREATE OR REPLACE FUNCTION read_accounting_member_statement(
 p_organization UUID,p_actor UUID,p_member UUID,p_currency TEXT,p_from DATE,p_to DATE,p_cutoff TIMESTAMPTZ DEFAULT NOW(),p_offset INTEGER DEFAULT 0,p_limit INTEGER DEFAULT 50
) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE account financial_accounts; opening BIGINT; page_opening BIGINT; closing BIGINT; total BIGINT; lines JSONB; cur TEXT:=upper(p_currency);
BEGIN
 IF cur IS NULL OR cur!~'^[A-Z]{3}$' OR p_from IS NULL OR p_to IS NULL OR p_from>p_to OR p_cutoff IS NULL OR p_cutoff>clock_timestamp() OR p_offset IS NULL OR p_offset<0 OR p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'ACCOUNTING_MEMBER_STATEMENT_REQUEST_INVALID'; END IF;
 IF NOT EXISTS(SELECT 1 FROM organization_memberships WHERE organization_id=p_organization AND user_id=p_member AND status='active') THEN RAISE EXCEPTION 'ACCOUNTING_MEMBER_STATEMENT_MEMBER_NOT_FOUND'; END IF;
 IF p_actor<>p_member AND NOT has_financial_permission(p_organization,p_actor,'financial.accounting.read') THEN RAISE EXCEPTION 'ACCOUNTING_MEMBER_STATEMENT_PERMISSION_DENIED'; END IF;
 IF p_actor=p_member AND NOT EXISTS(SELECT 1 FROM organization_memberships WHERE organization_id=p_organization AND user_id=p_actor AND status='active') THEN RAISE EXCEPTION 'ACCOUNTING_MEMBER_STATEMENT_PERMISSION_DENIED'; END IF;
 SELECT * INTO account FROM financial_accounts WHERE organization_id=p_organization AND owner_type='user' AND owner_id=p_member AND currency=cur AND purpose='individual_wallet_funds' ORDER BY effective_from DESC,created_at DESC LIMIT 1;
 IF account.id IS NULL THEN RAISE EXCEPTION 'ACCOUNTING_MEMBER_STATEMENT_ACCOUNT_NOT_FOUND'; END IF;
 SELECT COALESCE(sum(CASE WHEN line.side=account.normal_side THEN line.amount_minor ELSE -line.amount_minor END),0)::BIGINT INTO opening FROM journal_lines line JOIN journal_entries entry ON entry.id=line.journal_entry_id AND entry.organization_id=p_organization AND entry.currency=cur AND entry.status='posted' WHERE line.organization_id=p_organization AND line.currency=cur AND line.account_id=account.id AND entry.effective_date<p_from AND entry.posted_at<=p_cutoff AND entry.created_at<=p_cutoff;
 SELECT opening+COALESCE(sum(CASE WHEN side=account.normal_side THEN amount_minor ELSE -amount_minor END),0)::BIGINT INTO page_opening FROM(SELECT line.side,line.amount_minor FROM journal_lines line JOIN journal_entries entry ON entry.id=line.journal_entry_id AND entry.organization_id=p_organization AND entry.currency=cur AND entry.status='posted' WHERE line.organization_id=p_organization AND line.currency=cur AND line.account_id=account.id AND entry.effective_date BETWEEN p_from AND p_to AND entry.posted_at<=p_cutoff AND entry.created_at<=p_cutoff ORDER BY entry.effective_date,entry.posted_at,line.line_number,line.id LIMIT p_offset) preceding;
 SELECT opening+COALESCE(sum(CASE WHEN line.side=account.normal_side THEN line.amount_minor ELSE -line.amount_minor END),0)::BIGINT,count(*) INTO closing,total FROM journal_lines line JOIN journal_entries entry ON entry.id=line.journal_entry_id AND entry.organization_id=p_organization AND entry.currency=cur AND entry.status='posted' WHERE line.organization_id=p_organization AND line.currency=cur AND line.account_id=account.id AND entry.effective_date BETWEEN p_from AND p_to AND entry.posted_at<=p_cutoff AND entry.created_at<=p_cutoff;
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',page.id,'journalEntryId',page.journal_entry_id,'effectiveDate',page.effective_date,'postedAt',page.posted_at,'description',page.description,'sourceDomain',page.source_domain,'sourceRecordId',page.source_record_id,'correlationId',page.correlation_id,'side',page.side,'amountMinor',page.amount_minor::TEXT,'memo',page.memo) ORDER BY page.effective_date,page.posted_at,page.line_number,page.id),'[]'::JSONB) INTO lines FROM(SELECT line.*,entry.effective_date,entry.posted_at,entry.description,entry.source_domain,entry.source_record_id,entry.correlation_id FROM journal_lines line JOIN journal_entries entry ON entry.id=line.journal_entry_id AND entry.organization_id=p_organization AND entry.currency=cur AND entry.status='posted' WHERE line.organization_id=p_organization AND line.currency=cur AND line.account_id=account.id AND entry.effective_date BETWEEN p_from AND p_to AND entry.posted_at<=p_cutoff AND entry.created_at<=p_cutoff ORDER BY entry.effective_date,entry.posted_at,line.line_number,line.id OFFSET p_offset LIMIT p_limit) page;
 RETURN jsonb_build_object('organizationId',p_organization,'memberId',p_member,'account',jsonb_build_object('id',account.id,'code',account.code,'name',account.name,'currency',account.currency,'normalSide',account.normal_side),'from',p_from,'to',p_to,'cutoff',p_cutoff,'openingBalanceMinor',opening::TEXT,'pageOpeningBalanceMinor',page_opening::TEXT,'closingBalanceMinor',closing::TEXT,'lines',lines,'total',total);
END $$;
REVOKE ALL ON FUNCTION read_accounting_member_statement(UUID,UUID,UUID,TEXT,DATE,DATE,TIMESTAMPTZ,INTEGER,INTEGER) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION read_accounting_member_statement(UUID,UUID,UUID,TEXT,DATE,DATE,TIMESTAMPTZ,INTEGER,INTEGER) TO service_role;
