-- AC-07 cutoff-reproducible accounting journal audit export.
SET search_path=public,extensions;
CREATE OR REPLACE FUNCTION read_accounting_audit_export(p_organization UUID,p_actor UUID,p_currency TEXT,p_from DATE,p_to DATE,p_cutoff TIMESTAMPTZ DEFAULT NOW()) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE period accounting_periods; entries JSONB; cur TEXT:=upper(p_currency); entry_count BIGINT; line_count BIGINT;
BEGIN
 IF NOT has_financial_permission(p_organization,p_actor,'financial.accounting.read') THEN RAISE EXCEPTION 'ACCOUNTING_AUDIT_EXPORT_PERMISSION_DENIED'; END IF;
 IF cur IS NULL OR cur!~'^[A-Z]{3}$' OR p_from IS NULL OR p_to IS NULL OR p_from>p_to OR p_cutoff IS NULL OR p_cutoff>clock_timestamp() THEN RAISE EXCEPTION 'ACCOUNTING_AUDIT_EXPORT_REQUEST_INVALID'; END IF;
 SELECT * INTO period FROM accounting_periods WHERE organization_id=p_organization AND p_from>=starts_on AND p_to<=ends_on ORDER BY starts_on DESC LIMIT 1;
 IF period.id IS NULL THEN RAISE EXCEPTION 'ACCOUNTING_AUDIT_EXPORT_PERIOD_REQUIRED'; END IF;
 WITH selected AS(SELECT entry.id,entry.effective_date,entry.status,entry.source_domain,entry.source_record_id,entry.idempotency_key,entry.correlation_id,entry.description,entry.actor_id,entry.posted_at,entry.created_at FROM journal_entries entry WHERE entry.organization_id=p_organization AND entry.currency=cur AND entry.effective_date BETWEEN p_from AND p_to AND entry.posted_at<=p_cutoff AND entry.created_at<=p_cutoff), rendered AS(SELECT selected.*,COALESCE(jsonb_agg(jsonb_build_object('lineId',line.id,'accountId',line.account_id,'lineNumber',line.line_number,'side',line.side,'amountMinor',line.amount_minor::TEXT,'memo',line.memo) ORDER BY line.line_number,line.id),'[]'::JSONB) lines FROM selected LEFT JOIN journal_lines line ON line.journal_entry_id=selected.id AND line.organization_id=p_organization AND line.currency=cur GROUP BY selected.id,selected.effective_date,selected.status,selected.source_domain,selected.source_record_id,selected.idempotency_key,selected.correlation_id,selected.description,selected.actor_id,selected.posted_at,selected.created_at)
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'effectiveDate',effective_date,'status',status,'sourceDomain',source_domain,'sourceRecordId',source_record_id,'idempotencyKey',idempotency_key,'correlationId',correlation_id,'description',description,'actorId',actor_id,'postedAt',posted_at,'createdAt',created_at,'lines',lines) ORDER BY effective_date,posted_at,id),'[]'::JSONB),count(*),COALESCE(sum(jsonb_array_length(lines)),0) INTO entries,entry_count,line_count FROM rendered;
 RETURN jsonb_build_object('organizationId',p_organization,'currency',cur,'from',p_from,'to',p_to,'cutoff',p_cutoff,'period',jsonb_build_object('id',period.id,'name',period.name,'startsOn',period.starts_on,'endsOn',period.ends_on),'entryCount',entry_count,'lineCount',line_count,'entries',entries);
END $$;
REVOKE ALL ON FUNCTION read_accounting_audit_export(UUID,UUID,TEXT,DATE,DATE,TIMESTAMPTZ) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION read_accounting_audit_export(UUID,UUID,TEXT,DATE,DATE,TIMESTAMPTZ) TO service_role;
