import {Response} from 'express';
import Joi from 'joi';
import {TenantRequest} from '../middleware/tenant.js';
import {groupAdmissionService} from '../services/groupAdmissionService.js';
const key=(req:TenantRequest)=>{const value=req.header('Idempotency-Key');if(!value||!/^[A-Za-z0-9._:-]{8,128}$/.test(value))throw Object.assign(new Error('A valid Idempotency-Key header is required.'),{statusCode:400});return value;};
const context=(req:TenantRequest,groupId=req.params.id)=>({organizationId:req.tenant!.id,groupId,actorId:req.user!.id});
const uuid=(value:string)=>Joi.string().uuid().required().validate(value).error?null:value;
const initial=Joi.object({entryFeeAmountMinor:Joi.number().integer().min(0).max(100_000_000_000).required(),currency:Joi.string().valid('NGN').required(),requiredIdentityTier:Joi.string().valid('none','nin_verified').required(),eligibilityRules:Joi.object().unknown(true).default({})});
const admission=Joi.object({proposalId:Joi.string().uuid().required(),expectedMembershipVersion:Joi.number().integer().min(1).required()});
const status=(error:any)=>{if(error.statusCode)return error.statusCode;const m=error.message??'';if(m.includes('NOT_FOUND'))return 404;if(m.includes('IDENTITY_REQUIRED')||m.includes('PERMISSION'))return 403;if(m.includes('INVALID')||m.includes('REQUIRED')&&m.includes('ENTRY_REQUIREMENT'))return 400;if(m.includes('CONFLICT')||m.includes('NOT_DUE')||m.includes('MISMATCH')||m.includes('UNVERIFIED')||m.includes('CAPACITY')||m.includes('NOT_ACCEPTING')||m.includes('ALREADY_EXISTS'))return 409;return 500;};
const fail=(res:Response,error:any)=>res.status(status(error)).json({error:/^GROUP_[A-Z_]+$/.test(error.message??'')?error.message:error.statusCode===400?error.message:'Group admission command failed.'});
const body=(schema:Joi.ObjectSchema,value:unknown)=>{const result=schema.validate(value,{abortEarly:false,stripUnknown:true});if(result.error)throw Object.assign(new Error(result.error.message),{statusCode:400});return result.value;};
export const groupAdmissionController={
 async adoptInitial(req:TenantRequest,res:Response){try{const result=await groupAdmissionService.adoptInitialRequirements(context(req),{...body(initial,req.body),idempotencyKey:key(req)});return res.status(201).json({success:true,data:result});}catch(error){return fail(res,error);}},
 async execute(req:TenantRequest,res:Response){try{const memberId=uuid(req.params.memberId);if(!memberId)throw Object.assign(new Error('GROUP_MEMBERSHIP_ID_INVALID'),{statusCode:400});const result=await groupAdmissionService.executeAdmission(context(req),memberId,{...body(admission,req.body),idempotencyKey:key(req)});return res.json({success:true,data:result});}catch(error){return fail(res,error);}},
 async initializePayment(req:TenantRequest,res:Response){try{const memberId=uuid(req.body.member_id);if(!memberId)throw Object.assign(new Error('GROUP_MEMBERSHIP_ID_INVALID'),{statusCode:400});const groupId=uuid(req.body.group_id);if(!groupId)throw Object.assign(new Error('GROUP_ID_INVALID'),{statusCode:400});const result=await groupAdmissionService.initializeEntryPayment(context(req,groupId),memberId,req.user!.email,key(req));if(!result)return res.status(404).json({error:'Group membership not found'});return res.status(202).json({success:true,data:result});}catch(error){return fail(res,error);}},
 async getStatus(req:TenantRequest,res:Response){try{const memberId=uuid(req.params.memberId);if(!memberId)return res.status(400).json({error:'GROUP_MEMBERSHIP_ID_INVALID'});const result=await groupAdmissionService.getStatus(context(req),memberId);if(!result)return res.status(404).json({error:'Group membership not found'});return res.json({success:true,data:result});}catch(error){return fail(res,error);}},
 async getCurrentRequirements(req:TenantRequest,res:Response){try{const result=await groupAdmissionService.getCurrentRequirements(context(req));if(!result)return res.status(404).json({error:'Group entry requirements not found'});return res.json({success:true,data:result});}catch(error){return fail(res,error);}}
};
