import { Response } from 'express'; import Joi from 'joi';
import { CreateInvestmentProductCommand,InvestmentProductLifecycleCommand,InvestmentProductService,InvestmentProductValidationError,investmentProductService } from '../domains/financial/investmentProductService.js';
import { TenantRequest } from '../middleware/tenant.js';
const idempotencyKey=Joi.string().min(8).max(160).required();
const facts={issuerName:Joi.string().trim().min(2).max(160).required(),operatorName:Joi.string().trim().min(2).max(160).required(),underlyingReference:Joi.string().trim().min(3).max(200).required(),fundingTargetMinor:Joi.number().integer().min(1).required(),minimumSubscriptionMinor:Joi.number().integer().min(1).required(),maximumSubscriptionMinor:Joi.number().integer().min(1).required(),offerOpensAt:Joi.date().iso().required(),offerClosesAt:Joi.date().iso().required(),unitMethod:Joi.string().valid('fixed_unit_price','ownership_percentage').required(),unitPriceMinor:Joi.number().integer().min(1),oversubscriptionPolicy:Joi.string().valid('pro_rata','first_settled').required(),fees:Joi.array().required(),expectedReturnDisclosure:Joi.string().trim().min(12).max(500).required(),lossAllocationRule:Joi.object().required(),reportingSchedule:Joi.object().required(),maturityAt:Joi.date().iso().required(),exitRules:Joi.object().required(),jurisdictionEligibility:Joi.object().required(),riskDisclosureVersion:Joi.string().trim().min(1).max(80).required(),riskDisclosureHash:Joi.string().pattern(/^[a-f0-9]{64}$/).required(),conflictsDisclosure:Joi.string().trim().min(12).max(500).required()};
const createSchema=Joi.object({code:Joi.string().pattern(/^[A-Z0-9][A-Z0-9._-]{1,39}$/).required(),name:Joi.string().trim().min(2).max(160).required(),currency:Joi.string().pattern(/^[A-Z]{3}$/).required(),...facts,idempotencyKey});
const lifecycleSchema=Joi.object({version:Joi.number().integer().min(1).required(),idempotencyKey});
export class InvestmentProductController { constructor(private readonly service:InvestmentProductService=investmentProductService){}
 create=async(req:TenantRequest,res:Response)=>{const v=this.validate<Omit<CreateInvestmentProductCommand,'organizationId'|'actorId'>>(createSchema,req.body,res);if(!v)return;try{return res.status(201).json(await this.service.create({...v,organizationId:req.tenant!.id,actorId:req.user!.id}));}catch(e){return this.error(e,res);}};
 submit=async(req:TenantRequest,res:Response)=>this.lifecycle(req,res,'submit'); approve=async(req:TenantRequest,res:Response)=>this.lifecycle(req,res,'approve');
 private async lifecycle(req:TenantRequest,res:Response,action:'submit'|'approve'){const v=this.validate<Pick<InvestmentProductLifecycleCommand,'version'|'idempotencyKey'>>(lifecycleSchema,req.body,res);if(!v)return;try{const c={...v,organizationId:req.tenant!.id,actorId:req.user!.id,productId:req.params.productId};return res.json(action==='submit'?await this.service.submit(c):await this.service.approve(c));}catch(e){return this.error(e,res);}}
 private validate<T>(s:Joi.ObjectSchema,b:unknown,res:Response):T|undefined{const {error,value}=s.validate(b,{abortEarly:false,stripUnknown:true});if(!error)return value as T;res.status(400).json({success:false,error:'INVALID_INVESTMENT_PRODUCT_COMMAND',details:error.details.map(d=>d.message)});return undefined;}
 private error(e:unknown,res:Response){if(e instanceof InvestmentProductValidationError)return res.status(400).json({success:false,error:'INVALID_INVESTMENT_PRODUCT_COMMAND',message:e.message});return res.status(409).json({success:false,error:'INVESTMENT_PRODUCT_COMMAND_REJECTED',message:'The investment product command could not be completed in its current state.'});}
}
export const investmentProductController=new InvestmentProductController();
