import { Response } from 'express';
import Joi from 'joi';
import { LoanRepaymentReversalService, LoanRepaymentReversalValidationError, loanRepaymentReversalService } from '../domains/financial/loanRepaymentReversalService.js';
import { TenantRequest } from '../middleware/tenant.js';
const proposalSchema=Joi.object({reasonCode:Joi.string().pattern(/^[A-Z][A-Z0-9_]{2,39}$/).required(),reason:Joi.string().min(12).max(500).required(),evidenceReferences:Joi.array().min(1).required(),correlationId:Joi.string().uuid().required(),idempotencyKey:Joi.string().min(8).max(160).required()});
const decisionSchema=Joi.object({decision:Joi.string().valid('approve','reject').required(),reviewReason:Joi.string().min(12).max(500).required(),correlationId:Joi.string().uuid().required(),idempotencyKey:Joi.string().min(8).max(160).required()});
export class LoanRepaymentReversalController {
  constructor(private readonly service:LoanRepaymentReversalService=loanRepaymentReversalService) {}
  propose=async(req:TenantRequest,res:Response)=>{const {error,value}=proposalSchema.validate(req.body,{abortEarly:false,stripUnknown:true});if(error)return res.status(400).json({success:false,error:'INVALID_LOAN_REPAYMENT_REVERSAL_COMMAND',details:error.details.map(d=>d.message)});try{return res.status(201).json(await this.service.propose({organizationId:req.tenant!.id,actorId:req.user!.id,applicationId:req.params.applicationId,contractId:req.params.contractId,repaymentId:req.params.repaymentId,reasonCode:value.reasonCode,reason:value.reason,evidenceReferences:value.evidenceReferences,correlationId:value.correlationId,idempotencyKey:value.idempotencyKey}));}catch(caught){if(caught instanceof LoanRepaymentReversalValidationError)return res.status(400).json({success:false,error:'INVALID_LOAN_REPAYMENT_REVERSAL_COMMAND',message:caught.message});return res.status(409).json({success:false,error:'LOAN_REPAYMENT_REVERSAL_REJECTED',message:'The loan repayment reversal could not be processed in its current state.'});}};
  decide=async(req:TenantRequest,res:Response)=>{const {error,value}=decisionSchema.validate(req.body,{abortEarly:false,stripUnknown:true});if(error)return res.status(400).json({success:false,error:'INVALID_LOAN_REPAYMENT_REVERSAL_DECISION',details:error.details.map(d=>d.message)});try{return res.status(200).json(await this.service.decide({organizationId:req.tenant!.id,actorId:req.user!.id,reversalId:req.params.reversalId,decision:value.decision,reviewReason:value.reviewReason,correlationId:value.correlationId,idempotencyKey:value.idempotencyKey}));}catch(caught){if(caught instanceof LoanRepaymentReversalValidationError)return res.status(400).json({success:false,error:'INVALID_LOAN_REPAYMENT_REVERSAL_DECISION',message:caught.message});return res.status(409).json({success:false,error:'LOAN_REPAYMENT_REVERSAL_DECISION_REJECTED',message:'The loan repayment reversal decision could not be processed in its current state.'});}};
}
export const loanRepaymentReversalController=new LoanRepaymentReversalController();
