import { Router } from 'express';
import { accountingController } from '../controllers/accountingController.js';
import { dividendEntitlementController } from '../controllers/dividendEntitlementController.js';
import { accountingMemberStatementController } from '../controllers/accountingMemberStatementController.js';
import { accountingBudgetController } from '../controllers/accountingBudgetController.js';
import { accountingCashFlowController } from '../controllers/accountingCashFlowController.js';
import { accountingBalanceSheetController } from '../controllers/accountingBalanceSheetController.js';
import { authenticateToken } from '../middleware/auth.js';
import { requireFeature } from '../middleware/requireFeature.js';
import { requireTenantPermission, resolveTenant } from '../middleware/tenant.js';
const router=Router(); router.use(authenticateToken as any); router.use(resolveTenant);
router.get('/income-statement', requireFeature('financial.accounting.read'), requireTenantPermission('financial.accounting.read'), accountingController.incomeStatement);
router.get('/member-statement', requireFeature('financial.accounting.read'), accountingMemberStatementController.statement);
router.get('/budget-vs-actual', requireFeature('financial.accounting.read'), requireTenantPermission('financial.accounting.read'), accountingBudgetController.budgetVsActual);
router.get('/cash-flow', requireFeature('financial.accounting.read'), requireTenantPermission('financial.accounting.read'), accountingCashFlowController.cashFlow);
router.get('/balance-sheet', requireFeature('financial.accounting.read'), requireTenantPermission('financial.accounting.read'), accountingBalanceSheetController.balanceSheet);
router.post('/dividends/entitlements', requireFeature('financial.accounting.post'), requireTenantPermission('financial.accounting.post'), dividendEntitlementController.calculate);
router.post('/dividends/review', requireFeature('financial.accounting.post'), requireTenantPermission('financial.accounting.post'), dividendEntitlementController.review);
router.post('/dividends/approve', requireFeature('financial.rules.approve'), requireTenantPermission('financial.rules.approve'), dividendEntitlementController.approve);
router.post('/dividends/payable', requireFeature('financial.accounting.post'), requireTenantPermission('financial.accounting.post'), dividendEntitlementController.recognizePayable);
export default router;
