import { Router } from 'express';
import { authenticateToken } from '../middleware/auth.js';
import { resolveTenant, requireTenantRole } from '../middleware/tenant.js';
import { requireFeature } from '../middleware/requireFeature.js';
import { inventoryController } from '../controllers/inventoryController.js';
const router = Router();
router.use(authenticateToken, resolveTenant, requireFeature('farm_erp.operations'));
router.get('/', inventoryController.list);
router.post('/', requireTenantRole(['owner', 'admin', 'program_manager']), inventoryController.create);
router.post('/:id/movements', requireTenantRole(['owner', 'admin', 'program_manager']), inventoryController.move);
export default router;
