import { Router } from 'express'; import rateLimit from 'express-rate-limit';
import { investmentProductController } from '../controllers/investmentProductController.js'; import { investmentSubscriptionController } from '../controllers/investmentSubscriptionController.js'; import { authenticateToken } from '../middleware/auth.js'; import { requireFeature } from '../middleware/requireFeature.js'; import { requireTenantPermission,resolveTenant } from '../middleware/tenant.js';
const router=Router(); const limiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false,message:{success:false,error:'TOO_MANY_INVESTMENT_PRODUCT_COMMANDS'}});
router.use(authenticateToken as any);router.use(resolveTenant);
router.post('/products',requireFeature('financial.investments.configure'),requireTenantPermission('financial.investments.configure'),limiter,investmentProductController.create);
router.post('/products/:productId/submit',requireFeature('financial.investments.configure'),requireTenantPermission('financial.investments.configure'),limiter,investmentProductController.submit);
router.post('/products/:productId/approve',requireFeature('financial.investments.configure'),requireTenantPermission('financial.investments.configure'),limiter,investmentProductController.approve);
router.post('/products/:productId/open',requireFeature('financial.investments.subscribe'),requireTenantPermission('financial.investments.configure'),limiter,investmentProductController.open);
router.post('/products/:productId/subscriptions',requireFeature('financial.investments.subscribe'),requireTenantPermission('financial.investments.subscribe'),limiter,investmentSubscriptionController.create);
export default router;
