import { Router } from 'express';
import { authenticateToken } from '../middleware/auth.js';
import { resolveTenant, requireTenantRole } from '../middleware/tenant.js';
import { requireFeature } from '../middleware/requireFeature.js';
import { programmeController } from '../controllers/programmeController.js';
const router = Router();
router.use(authenticateToken, resolveTenant, requireFeature('institutional.government_dashboard'));
router.get('/', programmeController.list);
router.post('/', requireTenantRole(['owner', 'admin', 'program_manager']), programmeController.create);
router.get('/:id/cohorts', programmeController.listCohorts);
router.post('/:id/cohorts', requireTenantRole(['owner', 'admin', 'program_manager']), programmeController.createCohort);
router.get('/:id/benefits', programmeController.listBenefits);
router.post('/:id/benefits', requireTenantRole(['owner', 'admin', 'program_manager']), programmeController.createBenefit);
export default router;
