// SAV-04 governed withdrawals into personal wallets: lock-rule snapshots, fees or return forfeiture, liability reservations, maker-checker settlement, exactly-once recovery.
import React,{useEffect,useState}from'react';
import{RefreshCw}from'lucide-react';
import{savingsAPI}from'../services/savingsAPI';
import{savingsWithdrawalAPI,SavingsWithdrawal}from'../services/savingsWithdrawalAPI';
const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format((n||0)/100);
export default function SavingsWithdrawals(){const[accounts,setAccounts]=useState<any[]>([]),[selected,setSelected]=useState(''),[items,setItems]=useState<SavingsWithdrawal[]>([]),[reviews,setReviews]=useState<SavingsWithdrawal[]>([]),[amount,setAmount]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
const load=async()=>{try{const a=await savingsAPI.listEnrolments();setAccounts(a);const id=selected||a[0]?.enrolment.id||'';if(id){setSelected(id);setItems(await savingsWithdrawalAPI.list(id));}setReviews(await savingsWithdrawalAPI.reviews());}catch{setError('Savings withdrawals could not be loaded.');}};useEffect(()=>{void load();},[]);
const request=async(e:React.FormEvent)=>{e.preventDefault();try{const n=Math.round(Number(amount)*100);if(!Number.isSafeInteger(n)||n<1)throw new Error('Enter a valid amount.');await savingsWithdrawalAPI.request(selected,n);setNotice('Withdrawal requested and reserved for independent approval.');setAmount('');await load();}catch(e){setError(e instanceof Error?e.message:'The withdrawal could not be requested.');}};
const action=async(w:SavingsWithdrawal,a:'approve'|'reject'|'cancel')=>{try{if(a==='approve')await savingsWithdrawalAPI.approve(w.id);if(a==='reject')await savingsWithdrawalAPI.reject(w.id,'Withdrawal requires correction or additional evidence.');if(a==='cancel')await savingsWithdrawalAPI.cancel(w.id,'Member cancelled the pending withdrawal request.');setNotice('Withdrawal '+a+'d.');await load();}catch{setError('The withdrawal could not be '+a+'d.');}};
const currency=accounts.find(a=>a.enrolment.id===selected)?.enrolment.currency||'NGN';
return <main className="mx-auto max-w-6xl px-4 py-10"><div className="flex justify-between"><div><h1 className="text-3xl font-black">Savings withdrawals</h1><p className="mt-2 text-gray-600">Request a governed payout to your personal wallet with immutable lock and fee evidence.</p></div><button aria-label="Refresh withdrawals" onClick={()=>void load()} className="rounded border p-3"><RefreshCw size={18}/></button></div>{error&&<p role="alert" className="mt-4 rounded bg-red-50 p-3">{error}</p>}{notice&&<p role="status" className="mt-4 rounded bg-green-50 p-3">{notice}</p>}<section className="mt-6 rounded border bg-white p-5"><label>Savings account<select aria-label="Savings account" value={selected} onChange={e=>{setSelected(e.target.value);void savingsWithdrawalAPI.list(e.target.value).then(setItems);}} className="mt-2 block w-full rounded border p-3">{accounts.map(a=><option key={a.enrolment.id} value={a.enrolment.id}>{a.product.name}</option>)}</select></label><form onSubmit={request} className="mt-4 flex gap-3"><input aria-label="Withdrawal amount" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount" required className="rounded border p-3"/><button className="rounded bg-primary-700 px-4 py-3 font-bold text-white">Request withdrawal</button></form></section><section className="mt-8"><h2 className="text-xl font-bold">Your requests</h2><table className="mt-3 min-w-full rounded border bg-white text-left text-sm"><tbody>{items.map(w=><tr key={w.id} className="border-t"><td className="p-3">{money(w.requested_minor,currency)}</td><td className="p-3">{money(w.net_payout_minor,currency)}</td><td className="p-3">{w.state}</td><td className="p-3">{w.state==='pending_approval'&&<button onClick={()=>void action(w,'cancel')} className="rounded border px-3 py-1">Cancel</button>}</td></tr>)}</tbody></table></section><section className="mt-8"><h2 className="text-xl font-bold">Approval queue</h2><table className="mt-3 min-w-full rounded border bg-white text-left text-sm"><tbody>{reviews.map(w=><tr key={w.id} className="border-t"><td className="p-3">{money(w.requested_minor,w.currency)}</td><td className="p-3">{w.state}</td><td className="p-3">{w.state==='pending_approval'&&<><button onClick={()=>void action(w,'approve')} className="mr-2 rounded border px-3 py-1">Approve</button><button onClick={()=>void action(w,'reject')} className="rounded border px-3 py-1">Reject</button></>}</td></tr>)}</tbody></table></section></main>}
