-- INV-05 database contract: exact fixed-price allocation without new money movement.
SET search_path=public,extensions;
BEGIN;
DO $$
DECLARE org UUID; maker UUID; checker UUID; product UUID; intent UUID; late_intent UUID; settlement UUID; result JSONB; facts JSONB; failed BOOLEAN; journal UUID; journal_count BIGINT; unit_id UUID;
BEGIN
 SELECT organization_id,user_id INTO org,maker FROM organization_memberships WHERE role='owner' AND status='active' ORDER BY created_at LIMIT 1;
 INSERT INTO users(email,password,name,role) VALUES('inv05-checker-'||gen_random_uuid()||'@example.test','test','INV-05 Checker','farmer') RETURNING id INTO checker;
 INSERT INTO organization_memberships(organization_id,user_id,role,permissions,status,joined_at) VALUES(org,checker,'finance_manager',ARRAY['financial.investments.configure','financial.investments.service_existing'],'active',NOW());
 facts:=jsonb_build_object('issuerName','Farm Project Issuer','operatorName','Licensed Investment Operator','underlyingReference','farm-project-inv05','fundingTargetMinor',10000000,'minimumSubscriptionMinor',100000,'maximumSubscriptionMinor',2000000,'offerOpensAt','2026-09-01T00:00:00Z','offerClosesAt','2026-09-30T00:00:00Z','unitMethod','fixed_unit_price','unitPriceMinor',10000,'oversubscriptionPolicy','pro_rata','fees','[]'::JSONB,'expectedReturnDisclosure','Expected returns are estimates and are not guaranteed.','lossAllocationRule',jsonb_build_object('method','pro_rata_units'),'reportingSchedule',jsonb_build_object('frequency','quarterly'),'maturityAt','2027-09-30T00:00:00Z','exitRules',jsonb_build_object('earlyExit',FALSE),'jurisdictionEligibility',jsonb_build_object('countries',jsonb_build_array('NG'),'investorTypes',jsonb_build_array('individual')),'riskDisclosureVersion','INV-05.1','riskDisclosureHash',repeat('f',64),'conflictsDisclosure','The operator discloses all related-party interests.');
 result:=create_investment_product_draft(org,maker,'INV.FARM.05','INV-05 farm units','NGN',facts,'inv05-product-create','2026-08-14T10:00:00Z'); product:=(result->'product'->>'id')::UUID;
 PERFORM submit_investment_product(org,maker,product,1,'inv05-product-submit','2026-08-14T10:01:00Z'); PERFORM approve_investment_product(org,checker,product,1,'inv05-product-approve','2026-08-14T10:02:00Z'); PERFORM open_investment_product_offer(org,checker,product,1,'inv05-product-open','2026-09-15T11:59:00Z');
 intent:=(create_investment_subscription_intent(org,maker,product,500000,'NG','individual','INV-05.1',repeat('f',64),'00000000-0000-4000-8000-000000000501','inv05-subscribe-001','2026-09-15T12:00:00Z')->'subscription'->>'id')::UUID;
 late_intent:=(create_investment_subscription_intent(org,maker,product,100000,'NG','individual','INV-05.1',repeat('f',64),'00000000-0000-4000-8000-000000000506','inv05-subscribe-002','2026-09-15T12:00:30Z')->'subscription'->>'id')::UUID;
 SELECT post_wallet_journal(org,'investment.test.custody','inv05-settlement-source','INV-05 test settlement',jsonb_build_array(jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.BANK_CASH','Test bank cash','asset','debit'),'line_number',1,'side','debit','amount_minor',500000,'memo','INV-05 test cash'),jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.CLEARING.INV05','Test clearing','asset','debit'),'line_number',2,'side','credit','amount_minor',500000,'memo','INV-05 test clearing'))) INTO journal;
 PERFORM set_config('microfams.payment_engine','on',TRUE); INSERT INTO settlements(organization_id,provider_name,provider_environment,provider_reference,currency,gross_amount_minor,fee_amount_minor,net_amount_minor,source_hash,state,settled_at,journal_entry_id) VALUES(org,'deterministic','deterministic','inv05-provider-001','NGN',500000,0,500000,repeat('a',64),'posted','2026-09-15T12:01:00Z',journal) RETURNING id INTO settlement;
 PERFORM settle_investment_subscription(org,checker,intent,settlement,'00000000-0000-4000-8000-000000000502','inv05-settle-001','2026-09-15T12:02:00Z');
 SELECT count(*) INTO journal_count FROM journal_entries WHERE organization_id=org;
 failed:=FALSE; BEGIN PERFORM allocate_fixed_investment_units(org,checker,intent,'00000000-0000-4000-8000-000000000503','inv05-allocate-early','2026-09-30T00:00:00Z'); EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%not closed%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV05: allocation accepted before offer close'; END IF;
 result:=allocate_fixed_investment_units(org,checker,intent,'00000000-0000-4000-8000-000000000504','inv05-allocate-001','2026-10-01T00:00:00Z'); unit_id:=(result->'units'->>'id')::UUID;
 IF result->'subscription'->>'state'<>'allocated' OR (result->'units'->>'unit_count')::BIGINT<>50 OR (result->'units'->>'unit_price_minor')::BIGINT<>10000 OR (result->'units'->>'allocated_amount_minor')::BIGINT<>500000 THEN RAISE EXCEPTION 'INV05: fixed units were not allocated exactly'; END IF;
 IF (SELECT count(*) FROM journal_entries WHERE organization_id=org)<>journal_count OR NOT EXISTS(SELECT 1 FROM organization_audit_log WHERE organization_id=org AND action='INVESTMENT_UNITS_ALLOCATED' AND resource_id=intent::TEXT) THEN RAISE EXCEPTION 'INV05: allocation changed cash or omitted audit evidence'; END IF;
 IF (allocate_fixed_investment_units(org,checker,intent,'00000000-0000-4000-8000-000000000504','inv05-allocate-001','2026-10-02T00:00:00Z')->'units'->>'id')::UUID<>unit_id OR (SELECT count(*) FROM investment_units WHERE subscription_id=intent)<>1 THEN RAISE EXCEPTION 'INV05: allocation replay duplicated units'; END IF;
 failed:=FALSE; BEGIN UPDATE investment_units SET unit_count=51 WHERE id=unit_id; EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%immutable%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV05: unit evidence was mutable'; END IF;
 failed:=FALSE; BEGIN PERFORM set_config('microfams.investment_subscription_engine','on',TRUE); UPDATE investment_subscription_intents SET state='settled' WHERE id=late_intent; EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%allocation has already started%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV05: late settlement accepted after allocation started'; END IF;
 failed:=FALSE; BEGIN PERFORM allocate_fixed_investment_units(org,checker,intent,'00000000-0000-4000-8000-000000000505','inv05-allocate-again','2026-10-02T00:00:00Z'); EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%not settled%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV05: allocated subscription accepted with a new key'; END IF;
END $$;
ROLLBACK;
SELECT 'investment fixed-unit allocation schema tests passed' AS result;
