-- INV-04 database contract: bind one pending intent to exact posted provider settlement.
SET search_path=public,extensions;
BEGIN;
DO $$
DECLARE org UUID; maker UUID; checker UUID; product UUID; intent UUID; settlement UUID; result JSONB; facts JSONB; failed BOOLEAN; journal UUID; journal_count BIGINT;
BEGIN
 SELECT organization_id,user_id INTO org,maker FROM organization_memberships WHERE role='owner' AND status='active' ORDER BY created_at LIMIT 1;
 INSERT INTO users(email,password,name,role) VALUES('inv04-checker-'||gen_random_uuid()||'@example.test','test','INV-04 Checker','farmer') RETURNING id INTO checker;
 INSERT INTO organization_memberships(organization_id,user_id,role,permissions,status,joined_at) VALUES(org,checker,'finance_manager',ARRAY['financial.investments.configure','financial.investments.service_existing'],'active',NOW());
 facts:=jsonb_build_object('issuerName','Farm Project Issuer','operatorName','Licensed Investment Operator','underlyingReference','farm-project-inv04','fundingTargetMinor',10000000,'minimumSubscriptionMinor',100000,'maximumSubscriptionMinor',2000000,'offerOpensAt','2026-09-01T00:00:00Z','offerClosesAt','2026-09-30T00:00:00Z','unitMethod','fixed_unit_price','unitPriceMinor',10000,'oversubscriptionPolicy','pro_rata','fees','[]'::JSONB,'expectedReturnDisclosure','Expected returns are estimates and are not guaranteed.','lossAllocationRule',jsonb_build_object('method','pro_rata_units'),'reportingSchedule',jsonb_build_object('frequency','quarterly'),'maturityAt','2027-09-30T00:00:00Z','exitRules',jsonb_build_object('earlyExit',FALSE),'jurisdictionEligibility',jsonb_build_object('countries',jsonb_build_array('NG'),'investorTypes',jsonb_build_array('individual')),'riskDisclosureVersion','INV-04.1','riskDisclosureHash',repeat('d',64),'conflictsDisclosure','The operator discloses all related-party interests.');
 result:=create_investment_product_draft(org,maker,'INV.FARM.04','INV-04 farm units','NGN',facts,'inv04-product-create','2026-08-13T19:00:00Z'); product:=(result->'product'->>'id')::UUID;
 PERFORM submit_investment_product(org,maker,product,1,'inv04-product-submit','2026-08-13T19:01:00Z'); PERFORM approve_investment_product(org,checker,product,1,'inv04-product-approve','2026-08-13T19:02:00Z'); PERFORM open_investment_product_offer(org,checker,product,1,'inv04-product-open','2026-09-15T11:59:00Z');
 intent:=(create_investment_subscription_intent(org,maker,product,500000,'NG','individual','INV-04.1',repeat('d',64),'00000000-0000-4000-8000-000000000401','inv04-subscribe-001','2026-09-15T12:00:00Z')->'subscription'->>'id')::UUID;
 SELECT post_wallet_journal(org,'investment.test.custody','inv04-settlement-source','INV-04 test settlement',jsonb_build_array(jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.BANK_CASH','Test bank cash','asset','debit'),'line_number',1,'side','debit','amount_minor',500000,'memo','INV-04 test cash'),jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.CLEARING.INV04','Test clearing','asset','debit'),'line_number',2,'side','credit','amount_minor',500000,'memo','INV-04 test clearing'))) INTO journal;
 PERFORM set_config('microfams.payment_engine','on',TRUE); INSERT INTO settlements(organization_id,provider_name,provider_environment,provider_reference,currency,gross_amount_minor,fee_amount_minor,net_amount_minor,source_hash,state,settled_at,journal_entry_id) VALUES(org,'deterministic','deterministic','inv04-provider-001','NGN',500000,0,500000,repeat('e',64),'posted','2026-09-15T12:01:00Z',journal) RETURNING id INTO settlement;
 SELECT count(*) INTO journal_count FROM journal_entries WHERE organization_id=org;
 result:=settle_investment_subscription(org,checker,intent,settlement,'00000000-0000-4000-8000-000000000402','inv04-settle-001','2026-09-15T12:02:00Z');
 IF result->'subscription'->>'state'<>'settled' OR NOT EXISTS(SELECT 1 FROM investment_subscription_settlements WHERE subscription_id=intent AND settlement_id=settlement) OR NOT EXISTS(SELECT 1 FROM organization_audit_log WHERE organization_id=org AND action='INVESTMENT_SUBSCRIPTION_SETTLED' AND resource_id=intent::TEXT) OR (SELECT count(*) FROM journal_entries WHERE organization_id=org)<>journal_count THEN RAISE EXCEPTION 'INV04: settlement evidence incomplete or cash journal duplicated'; END IF;
 IF (settle_investment_subscription(org,checker,intent,settlement,'00000000-0000-4000-8000-000000000402','inv04-settle-001','2026-09-15T12:05:00Z')->'subscription'->>'id')::UUID<>intent THEN RAISE EXCEPTION 'INV04: settlement replay failed'; END IF;
 IF (SELECT count(*) FROM investment_subscription_settlements WHERE subscription_id=intent)<>1 OR to_regclass('public.investment_units') IS NOT NULL THEN RAISE EXCEPTION 'INV04: duplicate settlement or units created'; END IF;
 failed:=FALSE; BEGIN PERFORM settle_investment_subscription(org,checker,intent,settlement,'00000000-0000-4000-8000-000000000403','inv04-settle-bad','2026-09-15T12:06:00Z'); EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%not pending%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV04: settled subscription accepted again'; END IF;
END $$;
ROLLBACK;
SELECT 'investment subscription settlement schema tests passed' AS result;
