-- INV-06 database contract: deterministic oversubscription planning without execution.
SET search_path=public,extensions;
BEGIN;
DO $$
DECLARE org UUID; maker UUID; checker UUID; product UUID; first_intent UUID; second_intent UUID; late_intent UUID; first_settlement UUID; second_settlement UUID; first_journal UUID; second_journal UUID; created_plan UUID; result JSONB; facts JSONB; failed BOOLEAN; journal_count BIGINT;
BEGIN
 SELECT organization_id,user_id INTO org,maker FROM organization_memberships WHERE role='owner' AND status='active' ORDER BY created_at LIMIT 1;
 INSERT INTO users(email,password,name,role) VALUES('inv06-checker-'||gen_random_uuid()||'@example.test','test','INV-06 Checker','farmer') RETURNING id INTO checker;
 INSERT INTO organization_memberships(organization_id,user_id,role,permissions,status,joined_at) VALUES(org,checker,'finance_manager',ARRAY['financial.investments.configure','financial.investments.service_existing'],'active',NOW());
 facts:=jsonb_build_object('issuerName','Farm Project Issuer','operatorName','Licensed Investment Operator','underlyingReference','farm-project-inv06','fundingTargetMinor',500000,'minimumSubscriptionMinor',100000,'maximumSubscriptionMinor',400000,'offerOpensAt','2026-09-01T00:00:00Z','offerClosesAt','2026-09-30T00:00:00Z','unitMethod','fixed_unit_price','unitPriceMinor',100000,'oversubscriptionPolicy','pro_rata','fees','[]'::JSONB,'expectedReturnDisclosure','Expected returns are estimates and are not guaranteed.','lossAllocationRule',jsonb_build_object('method','pro_rata_units'),'reportingSchedule',jsonb_build_object('frequency','quarterly'),'maturityAt','2027-09-30T00:00:00Z','exitRules',jsonb_build_object('earlyExit',FALSE),'jurisdictionEligibility',jsonb_build_object('countries',jsonb_build_array('NG'),'investorTypes',jsonb_build_array('individual')),'riskDisclosureVersion','INV-06.1','riskDisclosureHash',repeat('b',64),'conflictsDisclosure','The operator discloses all related-party interests.');
 result:=create_investment_product_draft(org,maker,'INV.FARM.06','INV-06 farm units','NGN',facts,'inv06-product-create','2026-08-14T06:00:00Z'); product:=(result->'product'->>'id')::UUID;
 PERFORM submit_investment_product(org,maker,product,1,'inv06-product-submit','2026-08-14T06:01:00Z'); PERFORM approve_investment_product(org,checker,product,1,'inv06-product-approve','2026-08-14T06:02:00Z'); PERFORM open_investment_product_offer(org,checker,product,1,'inv06-product-open','2026-09-15T11:59:00Z');
 first_intent:=(create_investment_subscription_intent(org,maker,product,400000,'NG','individual','INV-06.1',repeat('b',64),'00000000-0000-4000-8000-000000000601','inv06-subscribe-001','2026-09-15T12:00:00Z')->'subscription'->>'id')::UUID;
 second_intent:=(create_investment_subscription_intent(org,maker,product,300000,'NG','individual','INV-06.1',repeat('b',64),'00000000-0000-4000-8000-000000000602','inv06-subscribe-002','2026-09-15T12:01:00Z')->'subscription'->>'id')::UUID;
 late_intent:=(create_investment_subscription_intent(org,maker,product,100000,'NG','individual','INV-06.1',repeat('b',64),'00000000-0000-4000-8000-000000000603','inv06-subscribe-003','2026-09-15T12:02:00Z')->'subscription'->>'id')::UUID;
 SELECT post_wallet_journal(org,'investment.test.custody','inv06-settlement-source-1','INV-06 first settlement',jsonb_build_array(jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.BANK_CASH','Test bank cash','asset','debit'),'line_number',1,'side','debit','amount_minor',400000,'memo','INV-06 cash'),jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.CLEARING.INV06','Test clearing','asset','debit'),'line_number',2,'side','credit','amount_minor',400000,'memo','INV-06 clearing'))) INTO first_journal;
 SELECT post_wallet_journal(org,'investment.test.custody','inv06-settlement-source-2','INV-06 second settlement',jsonb_build_array(jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.BANK_CASH','Test bank cash','asset','debit'),'line_number',1,'side','debit','amount_minor',300000,'memo','INV-06 cash'),jsonb_build_object('account_id',ensure_wallet_system_account(org,'PAYMENT.CLEARING.INV06','Test clearing','asset','debit'),'line_number',2,'side','credit','amount_minor',300000,'memo','INV-06 clearing'))) INTO second_journal;
 PERFORM set_config('microfams.payment_engine','on',TRUE);
 INSERT INTO settlements(organization_id,provider_name,provider_environment,provider_reference,currency,gross_amount_minor,fee_amount_minor,net_amount_minor,source_hash,state,settled_at,journal_entry_id) VALUES(org,'deterministic','deterministic','inv06-provider-001','NGN',400000,0,400000,encode(digest(convert_to('inv06-provider-001','UTF8'),'sha256'),'hex'),'posted','2026-09-15T12:03:00Z',first_journal) RETURNING id INTO first_settlement;
 INSERT INTO settlements(organization_id,provider_name,provider_environment,provider_reference,currency,gross_amount_minor,fee_amount_minor,net_amount_minor,source_hash,state,settled_at,journal_entry_id) VALUES(org,'deterministic','deterministic','inv06-provider-002','NGN',300000,0,300000,encode(digest(convert_to('inv06-provider-002','UTF8'),'sha256'),'hex'),'posted','2026-09-15T12:04:00Z',second_journal) RETURNING id INTO second_settlement;
 PERFORM settle_investment_subscription(org,checker,first_intent,first_settlement,'00000000-0000-4000-8000-000000000604','inv06-settle-001','2026-09-15T12:05:00Z');
 PERFORM settle_investment_subscription(org,checker,second_intent,second_settlement,'00000000-0000-4000-8000-000000000605','inv06-settle-002','2026-09-15T12:06:00Z');
 SELECT count(*) INTO journal_count FROM journal_entries WHERE organization_id=org;
 BEGIN
   PERFORM set_config('microfams.investment_product_engine','on',TRUE);
   UPDATE investment_product_versions SET oversubscription_policy='first_settled' WHERE product_id=product AND organization_id=org;
   result:=create_investment_allocation_plan(org,maker,product,'2026-09-30T00:01:00Z','00000000-0000-4000-8000-000000000607','inv06-first-plan-001','2026-10-01T00:00:00Z');
   IF (SELECT allocated_units FROM investment_allocation_plan_items WHERE plan_id=(result->'plan'->>'id')::UUID AND subscription_id=first_intent)<>4 OR (SELECT allocated_units FROM investment_allocation_plan_items WHERE plan_id=(result->'plan'->>'id')::UUID AND subscription_id=second_intent)<>1 OR (result->'plan'->>'refund_due_minor')::BIGINT<>200000 THEN RAISE EXCEPTION 'INV06: first-settled allocation is incorrect'; END IF;
   RAISE EXCEPTION 'INV06:first-settled-rollback';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'INV06:first-settled-rollback' THEN RAISE; END IF; END;
 result:=create_investment_allocation_plan(org,maker,product,'2026-09-30T00:01:00Z','00000000-0000-4000-8000-000000000606','inv06-plan-create-001','2026-10-01T00:00:00Z'); created_plan:=(result->'plan'->>'id')::UUID;
 IF result->'plan'->>'state'<>'draft' OR result->'plan'->>'policy'<>'pro_rata' OR (result->'plan'->>'available_units')::BIGINT<>5 OR (result->'plan'->>'allocated_units')::BIGINT<>5 OR (result->'plan'->>'refund_due_minor')::BIGINT<>200000 THEN RAISE EXCEPTION 'INV06: plan totals are incorrect'; END IF;
 IF (SELECT allocated_units FROM investment_allocation_plan_items WHERE plan_id=created_plan AND subscription_id=first_intent)<>3 OR (SELECT allocated_units FROM investment_allocation_plan_items WHERE plan_id=created_plan AND subscription_id=second_intent)<>2 THEN RAISE EXCEPTION 'INV06: largest-remainder allocation is incorrect'; END IF;
 IF (SELECT count(*) FROM journal_entries WHERE organization_id=org)<>journal_count OR EXISTS(SELECT 1 FROM investment_units WHERE product_id=product) THEN RAISE EXCEPTION 'INV06: planning executed money or units'; END IF;
 IF (create_investment_allocation_plan(org,maker,product,'2026-09-30T00:01:00Z','00000000-0000-4000-8000-000000000606','inv06-plan-create-001','2026-10-02T00:00:00Z')->'plan'->>'id')::UUID<>created_plan THEN RAISE EXCEPTION 'INV06: plan replay failed'; END IF;
 failed:=FALSE; BEGIN PERFORM approve_investment_allocation_plan(org,maker,created_plan,'inv06-plan-self-approve','2026-10-02T00:01:00Z'); EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%independent approval%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV06: maker approved own plan'; END IF;
 result:=approve_investment_allocation_plan(org,checker,created_plan,'inv06-plan-approve-001','2026-10-02T00:02:00Z');
 IF result->'plan'->>'state'<>'approved' OR NOT EXISTS(SELECT 1 FROM organization_audit_log WHERE organization_id=org AND action='INVESTMENT_ALLOCATION_PLAN_APPROVED' AND resource_id=created_plan::TEXT) THEN RAISE EXCEPTION 'INV06: approval evidence incomplete'; END IF;
 failed:=FALSE; BEGIN PERFORM set_config('microfams.investment_subscription_engine','on',TRUE); UPDATE investment_subscription_intents SET state='settled' WHERE id=late_intent; EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%planning has already started%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV06: late settlement accepted after planning'; END IF;
 failed:=FALSE; BEGIN UPDATE investment_allocation_plan_items SET allocated_units=4 WHERE plan_id=created_plan AND subscription_id=first_intent; EXCEPTION WHEN OTHERS THEN IF SQLERRM LIKE '%immutable%' THEN failed:=TRUE; END IF; END; IF NOT failed THEN RAISE EXCEPTION 'INV06: approved plan item was mutable'; END IF;
END $$;
ROLLBACK;
SELECT 'investment oversubscription planning schema tests passed' AS result;

