BEGIN;
DO $$
DECLARE creator UUID; reviewer UUID; approver UUID; accountant UUID; member_a UUID; member_b UUID; org UUID; source_period UUID; retained UUID; payable UUID; wallet_a UUID; wallet_b UUID; distribution UUID; result JSONB; replay JSONB; row dividend_distributions;
BEGIN
 INSERT INTO users(email,password,name,role) VALUES('div04-create-'||replace(gen_random_uuid()::TEXT,'-','')||'@example.test','test','DIV04 Creator','farmer') RETURNING id INTO creator;
 INSERT INTO users(email,password,name,role) VALUES('div04-review-'||replace(gen_random_uuid()::TEXT,'-','')||'@example.test','test','DIV04 Reviewer','farmer') RETURNING id INTO reviewer;
 INSERT INTO users(email,password,name,role) VALUES('div04-approve-'||replace(gen_random_uuid()::TEXT,'-','')||'@example.test','test','DIV04 Approver','farmer') RETURNING id INTO approver;
 INSERT INTO users(email,password,name,role) VALUES('div04-account-'||replace(gen_random_uuid()::TEXT,'-','')||'@example.test','test','DIV04 Accountant','farmer') RETURNING id INTO accountant;
 INSERT INTO users(email,password,name,role) VALUES('div04-a-'||replace(gen_random_uuid()::TEXT,'-','')||'@example.test','test','DIV04 A','farmer') RETURNING id INTO member_a;
 INSERT INTO users(email,password,name,role) VALUES('div04-b-'||replace(gen_random_uuid()::TEXT,'-','')||'@example.test','test','DIV04 B','farmer') RETURNING id INTO member_b;
 INSERT INTO organizations(name,slug,type,created_by) VALUES('DIV04 Tenant','div04-'||replace(gen_random_uuid()::TEXT,'-',''),'cooperative',creator) RETURNING id INTO org;
 INSERT INTO organization_memberships(organization_id,user_id,role,status,permissions,joined_at) VALUES(org,creator,'member','active',ARRAY['financial.accounting.post'],DATE '2027-01-01'),(org,reviewer,'member','active',ARRAY['financial.accounting.post'],DATE '2027-01-01'),(org,approver,'member','active',ARRAY['financial.rules.approve'],DATE '2027-01-01'),(org,accountant,'member','active',ARRAY['financial.accounting.post'],DATE '2027-01-01'),(org,member_a,'member','active','{}',DATE '2027-01-01'),(org,member_b,'member','active','{}',DATE '2027-01-01');
 INSERT INTO accounting_periods(organization_id,name,starts_on,ends_on,status) VALUES(org,'DIV04 FY 2027',DATE '2027-01-01',DATE '2027-12-31','closed') RETURNING id INTO source_period;
 INSERT INTO accounting_periods(organization_id,name,starts_on,ends_on,status) VALUES(org,'DIV04 FY 2028',DATE '2028-01-01',DATE '2028-12-31','open');
 INSERT INTO financial_accounts(organization_id,code,name,account_class,normal_side,currency,owner_type,is_control,created_by,purpose) VALUES(org,'DIV04.RETAINED','DIV04 retained','equity','credit','NGN','organization',TRUE,creator,'retained_surplus') RETURNING id INTO retained;
 INSERT INTO financial_accounts(organization_id,code,name,account_class,normal_side,currency,owner_type,is_control,created_by,purpose) VALUES(org,'DIV04.PAYABLE','DIV04 payable','liability','credit','NGN','organization',TRUE,creator,'dividends_payable') RETURNING id INTO payable;
 INSERT INTO financial_accounts(organization_id,code,name,account_class,normal_side,currency,owner_type,owner_id,is_control,created_by,purpose) VALUES(org,'DIV04.WALLET.A','DIV04 wallet A','liability','credit','NGN','user',member_a,TRUE,creator,'individual_wallet_funds') RETURNING id INTO wallet_a;
 INSERT INTO financial_accounts(organization_id,code,name,account_class,normal_side,currency,owner_type,owner_id,is_control,created_by,purpose) VALUES(org,'DIV04.WALLET.B','DIV04 wallet B','liability','credit','NGN','user',member_b,TRUE,creator,'individual_wallet_funds') RETURNING id INTO wallet_b;
 distribution:=calculate_dividend_entitlement_snapshot(org,creator,source_period,'fy2027_surplus','NGN',1001,100,DATE '2027-12-31',DATE '2028-02-01','{}',jsonb_build_array(jsonb_build_object('member_id',member_a,'paid_units',1),jsonb_build_object('member_id',member_b,'paid_units',2)),'div04-calc',clock_timestamp());
 PERFORM review_dividend_distribution(org,reviewer,distribution,'Distribution independently reviewed',clock_timestamp()); PERFORM approve_dividend_distribution(org,approver,distribution,clock_timestamp()); PERFORM recognize_dividend_payable(org,accountant,distribution,retained,payable,DATE '2028-02-01','div04-payable','00000000-0000-4000-8000-000000006401',clock_timestamp());
 result:=pay_dividend_distribution(org,accountant,distribution,DATE '2028-02-01','00000000-0000-4000-8000-000000006402',clock_timestamp()); replay:=pay_dividend_distribution(org,accountant,distribution,DATE '2028-02-01','00000000-0000-4000-8000-000000006402',clock_timestamp()); SELECT * INTO row FROM dividend_distributions WHERE id=distribution;
 IF row.state<>'paid' OR jsonb_array_length(row.payment_journal_ids)<>2 OR replay->>'state'<>'paid' OR (SELECT count(*) FROM journal_entries WHERE source_domain='dividend.payment' AND source_record_id IN(SELECT id::TEXT FROM dividend_entitlements WHERE distribution_id=distribution))<>2 OR (SELECT sum(CASE WHEN line.account_id=wallet_a OR line.account_id=wallet_b THEN line.amount_minor ELSE 0 END) FROM journal_lines line JOIN journal_entries entry ON entry.id=line.journal_entry_id WHERE entry.source_domain='dividend.payment')<>1000 THEN RAISE EXCEPTION 'DIV04 payment servicing invalid: row %, replay %, journals %, wallet total %',row,replay,(SELECT count(*) FROM journal_entries WHERE source_domain='dividend.payment'),(SELECT sum(CASE WHEN line.account_id=wallet_a OR line.account_id=wallet_b THEN line.amount_minor ELSE 0 END) FROM journal_lines line JOIN journal_entries entry ON entry.id=line.journal_entry_id WHERE entry.source_domain='dividend.payment'); END IF;
 BEGIN PERFORM pay_dividend_distribution(org,member_a,distribution,DATE '2028-02-01','00000000-0000-4000-8000-000000006403',clock_timestamp()); RAISE EXCEPTION 'unauthorized dividend payment accepted'; EXCEPTION WHEN OTHERS THEN IF SQLERRM='unauthorized dividend payment accepted' OR SQLERRM NOT LIKE '%DIVIDEND_PAYMENT_PERMISSION_DENIED%' THEN RAISE; END IF; END;
 IF has_function_privilege('authenticated','pay_dividend_distribution(uuid,uuid,uuid,date,uuid,timestamp with time zone)','EXECUTE') THEN RAISE EXCEPTION 'authenticated clients can bypass dividend payment boundary'; END IF;
END $$;
SELECT 'dividend payment servicing schema tests passed' AS result;
ROLLBACK;
