import { FeatureFlagDefinition } from '../types/featureFlags.js';

const flag = (
  key: string,
  domain: string,
  description: string,
  options: Partial<Pick<FeatureFlagDefinition, 'defaultEnabled' | 'failureMode' | 'risk'>> = {},
): FeatureFlagDefinition => ({
  key,
  domain,
  description,
  defaultEnabled: options.defaultEnabled ?? false,
  failureMode: options.failureMode ?? 'closed',
  risk: options.risk ?? 'standard',
});

export const FEATURE_FLAG_CATALOG: readonly FeatureFlagDefinition[] = [
  flag('groups.membership.manage', 'groups', 'Create groups and manage tenant-scoped memberships.', { defaultEnabled: true }),
  flag('groups.governance.manage', 'groups', 'Create and execute group governance decisions.'),
  flag('groups.contributions.accept_new', 'groups', 'Open contribution cycles and accept new group contributions.', { risk: 'regulated' }),
  flag('groups.contributions.service_existing', 'groups', 'Service, reconcile, refund, and report existing contributions.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('groups.treasury.create_disbursement', 'groups', 'Create new group treasury disbursement exposure.', { risk: 'regulated' }),
  flag('groups.treasury.service_existing', 'groups', 'Service, reconcile, reverse, and report existing group disbursements.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('groups.documents.download', 'groups', 'Issue short-lived download URLs for approved group documents.', { risk: 'provider' }),
  flag('groups.assets.manage', 'groups', 'Manage governed shared-asset custody and lifecycle.'),
  flag('booking.reservations.create', 'booking', 'Create atomic property reservation holds.', { defaultEnabled: true }),
  flag('booking.lifecycle.manage', 'booking', 'Approve and complete bookings through the canonical lifecycle command.', { defaultEnabled: true }),
  flag('booking.settlements.create', 'booking', 'Create new booking settlement obligations.', { risk: 'regulated' }),
  flag('booking.settlements.service_existing', 'booking', 'Service existing booking settlement obligations.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('booking.disputes.open', 'booking', 'Open new booking disputes.', { risk: 'regulated' }),
  flag('booking.disputes.service_existing', 'booking', 'Service existing booking disputes.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.payments.accept_new', 'payments', 'Accept new customer payment attempts.', { risk: 'regulated' }),
  flag('financial.payments.service_existing', 'payments', 'Process callbacks, reconciliation, refunds, and reversals for existing payments.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.payouts.create', 'payments', 'Create new beneficiary payouts.', { risk: 'regulated' }),
  flag('financial.payouts.service_existing', 'payments', 'Continue status updates and reconciliation for submitted payouts.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.wallets.transact', 'wallets', 'Create wallet credits, debits, and transfers.', { risk: 'regulated' }),
  flag('financial.wallets.read', 'wallets', 'Read balances, statements, and transaction history.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.escrow.create', 'escrow', 'Create and fund new escrow contracts.', { risk: 'regulated' }),
  flag('financial.escrow.service_existing', 'escrow', 'Release, refund, dispute, and report existing escrow obligations.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.savings.read', 'savings', 'Read available savings products, enrolments, balances, and statements.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.savings.enrol', 'savings', 'Open new savings enrolments.', { risk: 'regulated' }),
  flag('financial.savings.contribute', 'savings', 'Accept manual or mandate-based savings contributions.', { risk: 'regulated' }),
  flag('financial.savings.accrue', 'savings', 'Calculate and independently approve new savings return obligations.', { risk: 'regulated' }),
  flag('financial.savings.withdraw', 'savings', 'Service lawful withdrawals from existing savings enrolments.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.savings.service_existing', 'savings', 'Service contributions, statements, and lawful withdrawals for existing savings.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.savings.configure', 'savings', 'Draft, submit, and independently approve versioned savings products.', { risk: 'regulated' }),
  flag('financial.investments.read', 'investments', 'Read approved investment products.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.investments.configure', 'investments', 'Draft, submit, and independently approve investment products.', { risk: 'regulated' }),
  flag('financial.investments.subscribe', 'investments', 'Accept new investment subscriptions.', { risk: 'regulated' }),
  flag('financial.investments.service_existing', 'investments', 'Report, mature, settle, or write down existing investments.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.investments.refund_provider_submission', 'investments', 'Submit existing investment refund obligations through the original provider.', { risk: 'provider' }),
  flag('financial.loans.read', 'loans', 'Read active loan products and existing credit records.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.loans.configure', 'loans', 'Draft, revise, submit, and independently approve versioned loan products.', { risk: 'regulated' }),
  flag('financial.loans.originate', 'loans', 'Accept and decide new loan applications.', { risk: 'regulated' }),
  flag('financial.loans.disburse', 'loans', 'Create new loan disbursement exposure through an approved provider route.', { risk: 'regulated' }),
  flag('financial.loans.service_existing', 'loans', 'Service, collect, restructure, and report existing loans.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.dividends.declare', 'dividends', 'Calculate and approve new distributions.', { risk: 'regulated' }),
  flag('financial.dividends.service_existing', 'dividends', 'Pay, reconcile, and correct approved distributions.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.accounting.post', 'accounting', 'Post operational events to the tenant general ledger.', { risk: 'regulated' }),
  flag('financial.accounting.read', 'accounting', 'Read journals, statements, reconciliations, and reports.', { defaultEnabled: true, failureMode: 'open', risk: 'regulated' }),
  flag('financial.rules.approve', 'accounting', 'Approve regulated financial rules and maker-checker transitions.', { risk: 'regulated' }),
  flag('integration.paystack.live', 'payments', 'Route Paystack operations to live mode.', { risk: 'provider' }),
  flag('integration.interswitch.live', 'payments', 'Route Interswitch operations to live mode.', { risk: 'provider' }),
  flag('integration.organization_verification', 'identity', 'Submit organization registration evidence to an approved verification provider.', { risk: 'provider' }),
  flag('integration.identity_verification', 'identity', 'Use a government or licensed identity verification provider.', { risk: 'provider' }),
  flag('trust.review_cases', 'trust', 'Open, assign, and decide trust review cases.'),
  flag('trust.appeals', 'trust', 'File and decide independent trust appeals.'),
  flag('trust.suspended_account_recovery', 'trust', 'Issue single-purpose recovery links for suspended users to file appeals.', { risk: 'regulated' }),
  flag('trust.suspensions', 'trust', 'Apply decision-backed organization and membership suspensions.', { risk: 'regulated' }),
  flag('trust.legal_holds', 'trust', 'Place new legal holds; existing holds can always be released.', { risk: 'regulated' }),
  flag('trust.retention.dry_run', 'trust', 'Plan retention effects without changing source records.'),
  flag('trust.retention.execute', 'trust', 'Reserved destructive retention switch; no execution workflow is available.', { risk: 'regulated' }),
  flag('integration.sms', 'communications', 'Send messages through the configured SMS provider.', { risk: 'provider' }),
  flag('integration.weather', 'intelligence', 'Retrieve provider weather observations and forecasts.', { risk: 'provider' }),
  flag('integration.satellite', 'intelligence', 'Retrieve and process satellite imagery.', { risk: 'provider' }),
  flag('integration.ai_assistant', 'intelligence', 'Use the configured AI provider for assisted workflows.', { risk: 'provider' }),
  flag('institutional.government_dashboard', 'institutional', 'Expose programme dashboards to authorized government tenants.'),
  flag('institutional.ngo_dashboard', 'institutional', 'Expose programme dashboards to authorized NGO tenants.'),
  flag('farm_erp.operations', 'farm_erp', 'Enable full farm planning, inventory, labour, production, and cost workflows.'),
  flag('intelligence.agronomic_recommendations', 'intelligence', 'Generate tenant-scoped agronomic recommendations with provenance and confidence.', { risk: 'standard' }),
] as const;

export const FEATURE_FLAGS = new Map(FEATURE_FLAG_CATALOG.map((definition) => [definition.key, definition]));
